{
  "hash": "13e57686bfcd77fce9eb2dafd501f927",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Do student attendence effect their stress level?\"\nauthor: \"Yifeng Luo\"\ndate: \"2024-12-07\"\ncategories: [news, code, analysis]\nimage: \"tired.jpg\"\n---\n\n\n\nThis is a post with executable code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(viridis)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: viridisLite\n```\n\n\n:::\n\n```{.r .cell-code}\n# Read the data\ndata <- read.csv(\"student_monnitoring_data.csv\")\n\n# 1. Calculate average stress levels by attendance status\navg_stress <- data %>%\n  group_by(Attendance.Status) %>%\n  summarise(\n    mean_stress = mean(Stress.Level..GSR.),\n    sd_stress = sd(Stress.Level..GSR.),\n    count = n()\n  )\n\n# 2. Box plot of stress levels by attendance status\nggplot(data, aes(x = Attendance.Status, y = Stress.Level..GSR., fill = Attendance.Status)) +\n  geom_boxplot(alpha = 0.7) +\n  theme_minimal() +\n  labs(\n    title = \"Distribution of Stress Levels by Attendance Status\",\n    x = \"Attendance Status\",\n    y = \"Stress Level (GSR)\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3. Violin plot with points\nggplot(data, aes(x = Attendance.Status, y = Stress.Level..GSR., fill = Attendance.Status)) +\n  geom_violin(alpha = 0.5) +\n  geom_jitter(width = 0.2, alpha = 0.2) +\n  theme_minimal() +\n  labs(\n    title = \"Stress Level Distribution by Attendance Status\",\n    x = \"Attendance Status\",\n    y = \"Stress Level (GSR)\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 4. Bar plot of average stress levels\nggplot(avg_stress, aes(x = Attendance.Status, y = mean_stress, fill = Attendance.Status)) +\n  geom_bar(stat = \"identity\") +\n  geom_errorbar(aes(ymin = mean_stress - sd_stress, \n                    ymax = mean_stress + sd_stress),\n                width = 0.2) +\n  theme_minimal() +\n  labs(\n    title = \"Average Stress Levels by Attendance Status\",\n    x = \"Attendance Status\",\n    y = \"Average Stress Level (GSR)\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# 5. Create a summary table\nsummary_stats <- data %>%\n  group_by(Attendance.Status) %>%\n  summarise(\n    Count = n(),\n    Mean_Stress = mean(Stress.Level..GSR.),\n    Median_Stress = median(Stress.Level..GSR.),\n    SD_Stress = sd(Stress.Level..GSR.),\n    Min_Stress = min(Stress.Level..GSR.),\n    Max_Stress = max(Stress.Level..GSR.)\n  )\n\nprint(\"Summary Statistics:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Summary Statistics:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  Attendance.Status Count Mean_Stress Median_Stress SD_Stress Min_Stress\n  <chr>             <int>       <dbl>         <dbl>     <dbl>      <dbl>\n1 Absent             5002        2.74          2.72      1.31        0.5\n2 Late               5032        2.78          2.78      1.30        0.5\n3 Present            4966        2.77          2.79      1.30        0.5\n# ℹ 1 more variable: Max_Stress <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# 6. Perform ANOVA test\nanova_result <- aov(Stress.Level..GSR. ~ Attendance.Status, data = data)\nprint(\"\\nANOVA Results:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\nANOVA Results:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(anova_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Df Sum Sq Mean Sq F value Pr(>F)\nAttendance.Status     2      3   1.352   0.797   0.45\nResiduals         14997  25421   1.695               \n```\n\n\n:::\n\n```{.r .cell-code}\n# 7. Additional analysis: Relationship with sleep hours\nggplot(data, aes(x = Sleep.Hours, y = Stress.Level..GSR., color = Attendance.Status)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  facet_wrap(~Attendance.Status) +\n  theme_minimal() +\n  labs(\n    title = \"Relationship between Sleep Hours and Stress by Attendance Status\",\n    x = \"Sleep Hours\",\n    y = \"Stress Level (GSR)\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate correlation between sleep and stress for each attendance status\ncorrelations <- data %>%\n  group_by(Attendance.Status) %>%\n  summarise(\n    correlation = cor(Sleep.Hours, Stress.Level..GSR.)\n  )\n\nprint(\"\\nCorrelations between Sleep Hours and Stress Level by Attendance Status:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\nCorrelations between Sleep Hours and Stress Level by Attendance Status:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(correlations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Attendance.Status correlation\n  <chr>                   <dbl>\n1 Absent               -0.00292\n2 Late                  0.00480\n3 Present               0.00925\n```\n\n\n:::\n:::\n\n\n\nBased on the visualizations and statistical results, here's a comprehensive analysis of how attendance affects student stress levels:\n\n1.  Overall Stress Distribution (Box Plot & Violin Plot):\n\n-   The median stress levels are very similar across all attendance statuses (around 2.7-2.8)\n-   The spread of stress levels is consistent across all groups (standard deviation ≈ 1.3)\n-   The distribution shapes are nearly identical, suggesting attendance status doesn't strongly influence stress levels\n\n2.  Average Stress Levels:\n\n-   Absent students: 2.74 (SD = 1.31)\n-   Late students: 2.78 (SD = 1.30)\n-   Present students: 2.77 (SD = 1.30)\n-   The differences are minimal (less than 0.04 points between highest and lowest)\n\n3.  Statistical Significance:\n\n-   The ANOVA test results (F-value = 0.797, p-value = 0.45) indicate that:\n    -   There are no statistically significant differences in stress levels between attendance groups\n    -   The p-value \\> 0.05 suggests we cannot reject the null hypothesis\n\n4.  Sleep Hours and Stress Relationship:\n\n-   The correlations between sleep hours and stress are very weak for all groups:\n    -   Absent: -0.003 (slight negative correlation)\n    -   Late: 0.005 (slight positive correlation)\n    -   Present: 0.009 (slight positive correlation)\n-   These correlations are practically negligible\n\nOverall Conclusion: Based on this analysis, attendance status does not appear to have a meaningful effect on student stress levels. The stress distributions are remarkably similar across all attendance categories, and the statistical tests confirm that any observed differences are not significant. This suggests that other factors may be more important in determining student stress levels than attendance patterns.\n\nData Reference from:[link text](https://www.kaggle.com/datasets/ziya07/student-health-and-attendance-data)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}