{
  "hash": "41f4c3412b69118dc6e1c44f19f4ec45",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Do eduation effect their salary in IT area?\"\nauthor: \"Yifeng Luo\"\ndate: \"2024-12-07\"\ncategories: [news, code, analysis]\nimage: \"IT.jpg\"\n---\n\n\n\nThis is a post with executable code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\n# Assuming your data is in a CSV file named 'position_salary'\n# Read the data\nlibrary(readr)\n\ndata <- read_csv(\"position_salary.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 3467 Columns: 6\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): Position, Location, Gender, Education\ndbl (2): Experience (Years), Salary\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data %>% \n       group_by(Education) %>% \n       summarise(avg_salary = mean(Salary)), \n       aes(x = reorder(Education, avg_salary), y = avg_salary, fill = Education)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Average Salary by Education Level\",\n       x = \"Education\",\n       y = \"Average Salary\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2. Violin plot with box plot overlay\nggplot(data, aes(x = reorder(Education, Salary), y = Salary, fill = Education)) +\n  geom_violin(alpha = 0.5) +\n  geom_boxplot(width = 0.2, alpha = 0.8) +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Salary Distribution by Education Level\",\n       x = \"Education\",\n       y = \"Salary\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3. Density plot by education\nggplot(data, aes(x = Salary, fill = Education)) +\n  geom_density(alpha = 0.5) +\n  theme_minimal() +\n  labs(title = \"Salary Density Distribution by Education\",\n       x = \"Salary\",\n       y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# 4. Create a summary table\nsummary_stats <- data %>%\n  group_by(Education) %>%\n  summarise(\n    Count = n(),\n    Mean_Salary = mean(Salary),\n    Median_Salary = median(Salary),\n    Min_Salary = min(Salary),\n    Max_Salary = max(Salary),\n    SD_Salary = sd(Salary)\n  ) %>%\n  arrange(desc(Mean_Salary))\n\nprint(summary_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 × 7\n   Education     Count Mean_Salary Median_Salary Min_Salary Max_Salary SD_Salary\n   <chr>         <int>       <dbl>         <dbl>      <dbl>      <dbl>     <dbl>\n 1 Mtech             5    2086150.      2239942     1590856    2418385   361369.\n 2 B.PHARMACY        5    1979655.      2076047     1684091    2195626   203780.\n 3 BJMC              8    1846517.      1893824      887682    2489343   573794.\n 4 LLB              11    1815877.      1962283     1006036    2466419   546251.\n 5 B.Des.            8    1696488.      1767394.    1038609    2107011   357341.\n 6 bachelor of …     2    1637977       1637977      959279    2316675   959824.\n 7 B.Pharma          5    1542135.      1475416      539149    2314053   757287.\n 8 Diploma         147    1534798.      1499244      512503    2493345   597248.\n 9 BTECH             5    1517533       1783567      558228    2152921   623500.\n10 B.A             351    1510029.      1510050      502689    2497196   576255.\n# ℹ 11 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\n# 5. Box plot with individual points\nggplot(data, aes(x = reorder(Education, Salary), y = Salary, fill = Education)) +\n  geom_boxplot(alpha = 0.7) +\n  geom_jitter(width = 0.2, alpha = 0.3) +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Salary Distribution with Individual Data Points\",\n       x = \"Education\",\n       y = \"Salary\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# 6. Bar chart showing count of employees by education\nggplot(data, aes(x = reorder(Education, Education, FUN = length), fill = Education)) +\n  geom_bar() +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Number of Employees by Education Level\",\n       x = \"Education\",\n       y = \"Count\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-5.png){width=672}\n:::\n\n```{.r .cell-code}\n# Perform statistical test\n# ANOVA test to check if differences are significant\nanova_result <- aov(Salary ~ Education, data = data)\nprint(summary(anova_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df    Sum Sq   Mean Sq F value Pr(>F)\nEducation     19 7.762e+12 4.085e+11   1.226  0.226\nResiduals   3371 1.123e+15 3.333e+11               \n76 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n\nBased on the visualizations and statistical analysis, here's a comprehensive analysis of how education affects IT salaries in India:\n\nKey Findings:\n\n1.  Top Earning Degrees:\n\n-   MTech leads with the highest average salary (₹2,086,150)\n-   B.Pharmacy follows at ₹1,979,655\n-   BJMC ranks third at ₹1,846,517\n-   LLB comes fourth at ₹1,815,877\n\n2.  Distribution Patterns:\n\n-   Most degrees show wide salary ranges, indicating that factors beyond education influence compensation\n-   Technical degrees (MTech, B.PHARMACY) show more concentrated salary distributions\n-   General degrees (B.A, B.Com) show wider spread, suggesting more variable career paths\n\n3.  Employment Numbers:\n\n-   B.Tech/B.E. has the highest number of employees\n-   B.Sc, B.Com, and BCA follow as the next most common degrees\n-   Specialized degrees (MTech, B.PHARMACY, BJMC) have fewer representatives\n\n4.  Statistical Significance:\n\n-   ANOVA results (p-value = 0.226) suggest that the differences in salaries between education levels are not statistically significant at the 0.05 level\n-   This indicates that other factors (like experience, location, or specific skills) might play a more important role in determining salary\n\n5.  Salary Ranges:\n\n-   Most degrees show minimum salaries around ₹500,000-1,000,000\n-   Maximum salaries vary more significantly by degree\n-   Professional degrees (MTech, B.PHARMACY) show higher minimum salaries\n\nConclusions: 1. While higher technical degrees tend to command higher salaries, the relationship isn't statistically significant 2. There's considerable overlap in salary ranges across different education levels 3. Technical and professional degrees show more salary stability 4. Education alone isn't the sole determinant of IT salaries in India\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}